### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by Kliffe** [keyphact/pgoapi#13]
Hello Everybody!
(_At first i want say "sorry" for my bad english, becouse im from Poland)
I have an stupid question: "How should I instal those new updates on my Windows Phone? :) I hope I will get fast answear for this :p

**Comment by setanindo** [comment]
This not bot but api for etc like u looking, find other 3rd party

**Comment by DangerousHIV** [comment]
@setanindo what???

**Comment by Kliffe** [comment]
@setanindo What? XD I just need help from ppl who are a lot better than me in this thing :v

**Comment by xssc** [comment]
This is an API, also, an issue section, not support forum
