### ISSUE TITLE
Mac Help Needed

### ISSUE THREAD

**Issue by blackhattristar** [keyphact/pgoapi#15]
Helle, 

The "Crash" issue is getting a little busy so I thought I'd start an issue for just mac users so that anyone with the knowledge or know-how to get this repo to work with mac might be able to help us mac users! Any help would be greatly appreciated.

What are the known steps to take to get this working on mac?

**Comment by zaersk** [comment]
What you should do is recompile the source files as a .dylib (since you're on a Mac). The source files can be found here: https://github.com/SpencerSharkey/node-pogo-signature/tree/master/encrypt_src

**Comment by aurelian83** [comment]
could anyone guide me also from ZERO how to install this on MAC or WIN ? Thank you :)

**Comment by blackhattristar** [comment]
@aurelian83 Are you able to sign up for a Digital Ocean account? [Sign Up Here](https://m.do.co/c/dbc6f4dc88b0) and you get two months free and I can walk you through the steps. Step-by-step.

**Comment by wchill** [comment]
If you have a copy of `encrypt.c`, you can use this Makefile to compile `libencrypt.so`.

```
CC ?= cc
CFLAGS ?= -g -fPIC
LDFLAGS ?=

LIBENCRYPT_OBJS = encrypt.o
TEST_OBJS = main.o
OBJS = $(LIBENCRYPT_OBJS) $(TEST_OBJS)
TARGETS = libencrypt.so test

all: $(TARGETS)

libencrypt.so: $(LIBENCRYPT_OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -shared -o $@ $(LIBENCRYPT_OBJS) -lm

test: libencrypt.so $(TEST_OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -Wl -o $@ $(TEST_OBJS) -L$(CURDIR) -lencrypt 

lib: libencrypt.so

clean:
	$(RM) $(OBJS) $(TARGETS)
```
