### ISSUE TITLE
Unsure of how to get server running

### ISSUE THREAD

**Issue by Shda0w** [keyphact/pgoapi#16]
Hello All,

I think i have most of this setup but when i use the command:

C:\Users\USER\Desktop\pgoapi-master>"C:\Python27\python.exe" pokecli.py -a google -u INSERTUSER@gmail.com -p PASSWORD -l "MY LOCATION"

it looks like its running and at the end i get this:
                                            'status': 1}},
    'status_code': 2,
    'unknown6': [{   'response_type': 6, 'unknown2': {   'unknown1': 1L}}]}

Is this whats suppose to happen? When i try to open localhost:5000 is shows nothing is running.

What am i doing wrong?

**Comment by xssc** [comment]
Is there any error message after this? does the script end or do you have to stop it?

**Comment by Shda0w** [comment]
the script just ends

**Comment by xssc** [comment]
Hmm, not sure right now, I cant see an error

**Comment by wchill** [comment]
This is not a bot.
