### ISSUE TITLE
Debian problems

### ISSUE THREAD

**Issue by DrKinSlayeR** [keyphact/pgoapi#18]
Hi,
Firstly thanks for your work ! :D

When I launch the server I have this error "Exception while downloading map: Odd-length string". How I can resolve this problem ?

Thanks !

(sorry for my english)

**Comment by xssc** [comment]
What version of python are you using?

**Comment by wchill** [comment]
Did you pull the latest commits? I think this was fixed in #9.

**Comment by DrKinSlayeR** [comment]
python --version
Python 2.7.3

**Comment by DrKinSlayeR** [comment]
My bad I don't have the latest commits (3min ago). It's work now :D sorry and thanks for your help !
