### ISSUE TITLE
Replacement

### ISSUE THREAD

**Issue by IHG54** [keyphact/pgoapi#21]
Hello and a big thank you for your work !
I understand that it was not a bot , map etc.

My questions are ;
How to use pokecli ?
Because i have a error message
`Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pgoapi import pgoapi
  File "C:\Users\User\Documents\pgoapi-master\pgoapi\__init__.py", line 48, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3`

How to replace the API in a map file that I already have ?

I Thank You in advance for your future responses ,

cordially

**Comment by primaxius** [comment]
I suggest you contact that project's DEV.

**Comment by IHG54** [comment]
primaxius,
for the project of map it's
https://github.com/AHAAAAAAA/PokemonGo-Map

and for pokeclic this is what is provided in this case here

**Comment by rbryson74** [comment]
IHG54: please run   "pip install -r requirements.txt"  for pgoapi to upgrade protobuf to v3

**Comment by IHG54** [comment]
rbryon74

Thank you, i go to test

**Comment by IHG54** [comment]
Error .. :/

`Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\logins~1\\appdata\\local\\temp\\pip-build-yaukn_\\xxhash\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\logins~1\appdata\local\temp\pip-csx25w-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\logins~1\appdata\local\temp\pip-build-yaukn_\xxhash\`

**Comment by IHG54** [comment]
wchill don't close a post !
My questions isn't responses !
