### ISSUE TITLE
spiral_poi_search.py produces empty search results

### ISSUE THREAD

**Issue by hoodoos** [keyphact/pgoapi#27]
after number of logs like:
2016-08-07 12:15:37,080 [spiral_poi_search] [ INFO] Your given location: Starokonyushennyy per., 15, Moskva, Russia, 119002
2016-08-07 12:15:37,081 [spiral_poi_search] [ INFO] lat/long/alt: 55.7459158 37.5941288 0.0
2016-08-07 12:15:37,081 [    pgoapi] [ INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
2016-08-07 12:15:37,081 [auth_google] [ INFO] Google User Login for: natsverd623@gmail.com
2016-08-07 12:15:38,510 [auth_google] [ INFO] Google User Login successful.
2016-08-07 12:15:38,510 [auth_google] [ INFO] Request Google Access Token...
2016-08-07 12:15:38,821 [auth_google] [ INFO] Google Access Token successfully received.
2016-08-07 12:15:38,821 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
2016-08-07 12:15:38,822 [    pgoapi] [ INFO] Creating a new request...
2016-08-07 12:15:38,822 [    pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
2016-08-07 12:15:38,822 [    pgoapi] [ INFO] Adding 'GET_HATCHED_EGGS' to RPC request
2016-08-07 12:15:38,822 [    pgoapi] [ INFO] Adding 'GET_INVENTORY' to RPC request
2016-08-07 12:15:38,822 [    pgoapi] [ INFO] Adding 'CHECK_AWARDED_BADGES' to RPC request
2016-08-07 12:15:38,823 [    pgoapi] [ INFO] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
2016-08-07 12:15:38,823 [    pgoapi] [ INFO] Execution of RPC
2016-08-07 12:15:40,555 [    pgoapi] [ INFO] API Endpoint redirect... re-execution of call
2016-08-07 12:15:40,896 [    pgoapi] [ INFO] Cleanup of request!
2016-08-07 12:15:40,896 [    pgoapi] [ INFO] Finished RPC login sequence (app simulation)
2016-08-07 12:15:40,896 [    pgoapi] [ INFO] Login process completed
2016-08-07 12:15:40,897 [    pgoapi] [ INFO] Creating a new direct request...
2016-08-07 12:15:40,897 [    pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
2016-08-07 12:15:40,897 [    pgoapi] [ INFO] Execution of RPC
2016-08-07 12:15:41,337 [    pgoapi] [ INFO] Cleanup of request!
Response dictionary:
{   'request_id': 297544394269697283L,
    'responses': {   'GET_PLAYER': {   'player_data': {   'contact_settings': {   },
                                                          'creation_timestamp_ms': 1470560630159L,
                                                          'currencies': [   {   'name': u'POKECOIN'},
                                                                            {   'name': u'STARDUST'}],
                                                          'daily_bonus': {   },
                                                          'equipped_badge': {   },
                                                          'max_item_storage': 350,
                                                          'max_pokemon_storage': 250,
                                                          'username': u'natsverd623'},
                                       'success': True}},
    'status_code': 1}
2016-08-07 12:16:06,324 [    pgoapi] [ INFO] Creating a new direct request...
2016-08-07 12:16:06,324 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
2016-08-07 12:16:06,325 [    pgoapi] [ INFO] Execution of RPC
2016-08-07 12:16:06,760 [    pgoapi] [ INFO] Cleanup of request!

as a result I get:
POI dictionary:
{   'forts': [], 'pokemons': {   }}

**Comment by chaipokoi** [comment]
Have a look [here #176](https://github.com/tejado/pgoapi/issues/176https://github.com/tejado/pgoapi/issues/176)

**Comment by jmangeja1** [comment]
Were you able to resolve this problem? I can't see pokemon or forts with get_map_objects

**Comment by Vo0oX** [comment]
2016-08-07 15:45:37,188 [    pgoapi] [ INFO] Creating a new direct request...
2016-08-07 15:45:37,188 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
2016-08-07 15:45:37,190 [    pgoapi] [ INFO] Execution of RPC
2016-08-07 15:45:38,019 [    pgoapi] [ INFO] API Endpoint redirect... re-execution of call
2016-08-07 15:45:38,181 [    pgoapi] [ INFO] Cleanup of request!
Response dictionary (get_player): 
{   'request_id': 319013341259611202L,
    'responses': {   'GET_MAP_OBJECTS': {   'map_cells': [   {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595442848563200L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595436406112256L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595438553595904L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595440701079552L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926594978992095232L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926594981139578880L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926594983287062528L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926594985434546176L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926594970402160640L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926594974697127936L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926594976844611584L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595554517712896L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595556665196544L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595558812680192L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595560960163840L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595580287516672L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595582435000320L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595584582483968L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595586729967616L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595571697582080L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595578140033024L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595597467385856L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595599614869504L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595601762353152L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595603909836800L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595588877451264L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595591024934912L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595593172418560L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595595319902208L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595614647255040L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595616794738688L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595618942222336L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595621089705984L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595606057320448L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595608204804096L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595610352287744L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595612499771392L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595631827124224L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595633974607872L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595636122091520L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595638269575168L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595623237189632L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595625384673280L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595627532156928L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595629679640576L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595649006993408L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595651154477056L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595653301960704L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595655449444352L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595640417058816L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595642564542464L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595644712026112L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595646859509760L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595657596928000L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595659744411648L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595687661699072L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595689809182720L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595737053822976L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595739201306624L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595741348790272L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595752086208512L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595743496273920L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595745643757568L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595747791241216L},
                                                             {   'current_timestamp_ms': 1470573938211L,
                                                                 's2_cell_id': 9926595749938724864L}],
                                            'status': 1}},
    'status_code': 1,
    'unknown6': [{   'response_type': 6, 'unknown2': {   'unknown1': 1L}}]}




how fix ?

**Comment by dacay** [comment]
I am having similar results, now maximum radius seems to be increased but still no forts, etc from get_map_objects?

**Comment by sunkillerqc** [comment]
How fix 

 pgoapi] [ INFO] Cleanup of request!
Response dictionary:
{ 'request_id': 297544394269697283L,
'responses': { 'GET_PLAYER': { 'player_data': { 'contact_settings': { },

**Comment by hanlulong** [comment]
The utility script has been updated. Using the new utility file solved my problem. https://github.com/keyphact/pgoapi/blob/master/pgoapi/utilities.py

**Comment by jmangeja1** [comment]
I'm using that updated utility file, but im still only getting the s2_cell_ids and no forts or pokemon. Any ideas?

**Comment by gadzair** [comment]
+1; I'm getting empty results as well on master.

**Comment by dnsBlah** [comment]
same here

**Comment by jmangeja1** [comment]
Figured it out....... 
It sucked figuring it out so I am going to describe the process I took to fixing it.


1. Download http://pastebin.com/raw/fCSw0Fz4 as encrypt.c
2. Compile to .so  (gcc -shared -o encrypt.so -fPIC encrypt.c)
3. Edit ~/pgoapi-master/pgoapi/pygoapi.py
insert this line in the __init__ method of PGoApi:
self.__signature_lib = "encrypt.so"

4. Copy encrypt.so into same directory as the python program you are running OR include it in path

5. DONE!!! IT WORKS!

**Comment by jmangeja1** [comment]
@dnsBlah 
Also I forgot to mention....

5. uninstall pygoapi (pip uninstall pygoapi)
6. reinstall python setup.py install

**Comment by MrManiak** [comment]
Make sure the script does api.activate_signature("encrypt.dll") before requesting map objects. Make sure you have the dll in the script's folder.

**Comment by baskettcase** [comment]
@jmangeja1 I get "66 warnings generated." when creating the .so.. but it does create it.. Im hoping that's ok?

**Comment by ChrismCruz** [comment]
@jmangeja1 
I'm getting the following attribute error after (1) copying the code at http://pastebin.com/raw/fCSw0Fz4 into sublime text and saving it as encrypt.c, (2) compiling it into .so (gcc -shared -o encrypt.so -fPIC encrypt.c) (3) Replacing "self.__signature_lib = None" with "self.__signature_lib = 'encrypt.so'" within the pgoapi.py file (4) Copying the encrypt.so into the same directory as where my example python script lives (5) Uninstalled pygoapi (6) Ran 'python setup.py install' 

However, I'm getting the below error so I'm not sure what I did wrong or if I missed something

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1531, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 938, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Shippy/API/poke_api.py", line 228, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Shippy/API/poke_api.py", line 126, in main
    if not api.login(config.auth_service, config.username, config.password):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pgoapi-1.1.6-py2.7.egg/pgoapi/pgoapi.py", line 166, in login
    response = self.app_simulation_login()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pgoapi-1.1.6-py2.7.egg/pgoapi/pgoapi.py", line 143, in app_simulation_login
    response = request.call()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pgoapi-1.1.6-py2.7.egg/pgoapi/pgoapi.py", line 210, in call
    lib_path = self.__parent__.get_signature_lib()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pgoapi-1.1.6-py2.7.egg/pgoapi/pgoapi.py", line 118, in get_signature_lib
    return self._signature_lib
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pgoapi-1.1.6-py2.7.egg/pgoapi/pgoapi.py", line 129, in __getattr__
    raise AttributeError
AttributeError
```

**Comment by jmangeja1** [comment]
@baskettcase Yes it is ok with the warnings

**Comment by jmangeja1** [comment]
@ChrismCruz take a look at line "return self._signature_lib"    that error is arising because there is no variable called _signature_lib in your pgoapi class.

**Comment by baskettcase** [comment]
@jmangeja1 awesome thank you, this is the first time that I've actually had pokemon in my response! woot! now I need to figure out how to use this library with PHP (a language I actually know how to use :)) Thanks again!

**Comment by xakiru** [comment]
Where can I find the encrypt.dll Please ?

**Comment by jmangeja1** [comment]
@xakiru if you are using linux you need .so. If you are using windows, you need .dll
YOu can find encrypt.c at the link I posted earlier. Compile it to .dll or .so depending on machine

**Comment by xakiru** [comment]
@jmangeja1 Thank you, I'm not with an other issue once I try to activate signature

```
Traceback (most recent call last):
  File "pf.py", line 206, in <module>
    main()
  File "pf.py", line 125, in main
    api.activate_signature("encrypt.so")
  File "/home/divisi0n/public_html/pokemon/pgoapi/pgoapi/pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError

```

I'm calling the activate just before proceeding with map calls
```
    api.activate_signature("encrypt.so")
    find_poi(api, position[0], position[1])
```

Thanks,

**Comment by elliottcarlson** [comment]
@xakiru are you using the right pgoapi? This indicates that the method doesn't exist in the version you are using.

**Comment by cheesynoob** [comment]
Jmangela's solution should work for the invalid/missing file problems. Anything else create a new issue.

**Comment by JoKre17** [comment]
Maybe i didnt understand everything, but if i am right, we mixed up 2 projects here?
pgoapi and pokemonathome ?

So referring to the original topic of this issue, ofc. it is not possible to activate any signature if the function is not in the api.

But does anybody else know why there is still this "bug", that no pokemon seem to be in s2_cells ?
And maybe a workaround / how to fix?

I'd be very thankful! :D

**Comment by and7ey** [comment]
Is this is intentionally not covered in the README/documentation? And sample file comes with `api.activate_signature("encrypt.so")`...
