### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by daoreoofdoom** [keyphact/pgoapi#28]
what am I supposed to do after I download this?? I downloaded the original bot and I keep getting bad authentication error help please

**Comment by Cryxon** [comment]
https://github.com/keyphact/pgoapi/blob/master/README.md
Please read this before posting bullshit.
This is not a forum...

**Comment by daoreoofdoom** [comment]
How the fuck am I posting bullshit dickhead

**Comment by vincentcsm** [comment]
yes Sir 
you are posting Bullshit here

**Comment by daoreoofdoom** [comment]
Explain how dickhead

**Comment by omaryoss312** [comment]
dude seriously stop embarrassing yourself and just simply get out.
this is not the fkin bot retard! if you cant figure that out yourself you shouldnt be here in the first place!

**Comment by honnes** [comment]
Gosh... I never felt the urge to reply on someone who is whining.. but seriously... I feel like screaming "bloody hell daoreoofdoom", you joined github today just to complain like a little retard and not showing any kind of appreciation or respect. 

Please go outside, or bother your mom with this nonsense of yours. I would eat my hat if there's any proof on the internet that you're older than 10.....

Blessed sunday all.
