### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by FaustsDaemon** [keyphact/pgoapi#31]
Hi,
Sorry I know this isn't the right place for this question. I know this isn't a bot, it's just an api. But I have absolutely no idea how to implement this with the bot I'm using and there is very little help on the wiki page. Could anyone post some links or perhaps just quickly sum up how to use this. Thank you.

**Comment by chaipokoi** [comment]
I think you just have to wait an update for your bot. 
An api is not for end-user like you, but for devs :)

**Comment by FaustsDaemon** [comment]
Okay thank you very much :)
