### ISSUE TITLE
Possible memory leak using get_map_objects()

### ISSUE THREAD

**Issue by Wouter93** [keyphact/pgoapi#33]
After trying to run a fairly  large scan, I noticed memory usage kept increasing at quite a steady pace.  After some debugging and commenting things out, I found that get_map_objects() is the culprit.

Code usage (example):
`for _ in range(100):`
`    response_dict = api.get_map_objects(lat, long, timestamps, cell_ids)`
`    response_dict = {}`
 `time.sleep(5)`

Even though response_dict is (probably)  garbage collected,  memory usage keeps increasing with every iteration

After some more looking, I believe _make_rpc() is causing most of the memory usage.  I guess it might just be an issue in the requests library, combined with the fact that every 'api request' creates a new session.

**Comment by Wouter93** [comment]
Creating sessions was the culprit.  It seems python doesn't handle cleaning up sessions very well, so they linger in memory.

I resolved it by reusing the session objects

**Comment by tienthanhdhcn** [comment]
How did you do that to change to use a single session object?
