### ISSUE TITLE
Can not open so

### ISSUE THREAD

**Issue by alxnegrila** [keyphact/pgoapi#35]
return PGoApiRequest.call(self)
  File "pgoapi/pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "pgoapi/rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 438, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: encrypt.so: cannot open shared object file: No such file or directory

**Comment by alxnegrila** [comment]
I've runned wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make && mv libencrypt.so ../../encrypt.so with no results...

**Comment by Morl0ck** [comment]
Did you point to your download location of encrypt.so in the pokecli.py file?

https://github.com/keyphact/pgoapi/blob/master/pokecli.py#L123

**Comment by cheesynoob** [comment]
Morl0ck is right you need to specify the path
