### ISSUE TITLE
Still not seeing forts

### ISSUE THREAD

**Issue by dacay** [keyphact/pgoapi#36]
Hi there, I am using my own script to farm a nearby PokeStop but I can't see anything using the get_map_objects.

Is there anything different I should do to use the new proto correctly?

**Comment by hanlulong** [comment]
The utility script has been updated. Using the new utility file solved my problem. https://github.com/keyphact/pgoapi/blob/master/pgoapi/utilities.py

**Comment by JoKre17** [comment]
I'm trying to test spiral_poi_search, but it seems to never find any pokemon nor forts.
(Should be guaranteed, that where it searched, is a fort included)

I've tried to print the map_cells from response_dict['responses']['GET_MAP_OBJECTS']['map_cells'] but it never has "wild_pokmons" as a key in it. (should also be guaranteed that there are pokemon.)

Can somebody tell me what i might be doing wrong?

**Comment by crispmark** [comment]
Can anyone point out what is wrong with this?
```
api = pgoapi.PGoApi()
api.set_position(40.758631, -73.985105, 0.0)
api.login('ptc', '***', '***')
cell_ids = pgoapi.utilities.get_cell_ids(40.758631, -73.985105)
timestamps = [0,] * len(cell_ids)
time.sleep(0.51)
response_dict = api.get_map_objects(latitude = pgoapi.utilities.f2i(40.758631), longitude = pgoapi.utilities.f2i(-73.985105), since_timestamp_ms = timestamps, cell_id = cell_ids)
print('Response dictionary: \n\r{}'.format(pprint.PrettyPrinter(indent=4).pformat(response_dict)))
```

**Comment by dacay** [comment]
For future reference to others; problem solved by compiling and explicitly configuring PGoAPI object to use encrypt.so file which seems to be not documented anywhere.
