### ISSUE TITLE
Moron in need of help!

### ISSUE THREAD

**Issue by yuneedmyname** [keyphact/pgoapi#37]
First, let me say this: You people fucking rock! You have no idea how much I appreciate all of the time and effort you have put into this, and there is no way I can communicate it to you. It's not just about a game, for me... it's about you all, busting your asses, to A) "defeat 'the man'". B) Help those of us who want/need help. C) figuring out the puzzle and/or proving yourself/ves against opponents of "superior" strength... whatever the case is for you, personally, I applaud you!

Now, onto my small issue... 

I'm a complete moron where programming is concerned. I use Python only because there are certain programs that I use that require it, but I have never installed it before today, and I am even more inept with computer languages than I am with human languages (been living in Czech Republic for 11 years and have learned 3 phrases "nemluvim Cesky" = "I don't speak Czech". "Velke pivo" = "Large beer". "Jeste jedno" = "Another one"). 

So, here's my request: Would it be possible for someone/anyone to post some instructions for those of us whose computer skills go no further than playing games and searching for porn? Due to this work, I've finally installed Python (3.5.2 on Windows 10 [yes, willingly, bite me!] and I'm willing to learn... whether I'm able remains to be seen...

**Comment by JoKre17** [comment]
I'm also beginner, 
but if you're ready to use VM Ware, which in my opinion makes things way easier, you can just download VMware Player and e.g. Ubuntu v. 16.x. iso.

Then install VMware Player, start it.
Install the downloaded Ubuntu in your Player by clicking "Create a new virtual machine".
Follow the easy step-by-step the player gives you.
In the end your player should display the login window for ubuntu.
After login press "Strg"+"Alt"+"T":
Type:
   sudo apt-get update
   sudo apt install python-dev
   sudo apt install git (confirm with Y)
   
now [visit:](https://github.com/tejado/pgoapi/wiki/Installation) 
follow the steps "Alternative: setup.py installation"
   
Congratulations! Now you've installed the pgoapi!

You can now take a closer look to pokecli.py which should explain everything.
In addition ofc. visit the [Wiki](https://github.com/tejado/pgoapi/wiki/)

**Comment by yuneedmyname** [comment]
This looks interesting... Looks like I get to try something new! :) Thanks!
