### ISSUE TITLE
Undocumented requirement

### ISSUE THREAD

**Issue by cicatiello** [keyphact/pgoapi#38]
the new xxhash module on win enviroments need this to work properly

https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266

This should be documented as well

**Comment by cheesynoob** [comment]
You need that for PIP to work correctly..

**Comment by xssc** [comment]
^Lolllllll

**Comment by cicatiello** [comment]
@cheesynoob, it is not correct: pip works fine without when module does not require compilation. If module require compilation then you need compilation tool which pip clearly does not provide oob

**Comment by elliottcarlson** [comment]
That is still a pip dependency specifically.

**Comment by cicatiello** [comment]
@elliottcarlson didn't find anything related to pip and compilation [@pip doc](https://packaging.python.org/current/)
