### ISSUE TITLE
Is it possible to complete the tutorial with the current API?

### ISSUE THREAD

**Issue by jjordantb** [keyphact/pgoapi#39]
Looking over the documentation, it isn't very intuitive, and with some testing I can't figure out how.

Any help please?

**Comment by jjordantb** [comment]
Better question (with what I think is the correct terminology), how does one pass a protobuff struct into a function, example set_avatar(player_avatar=??)? How do I initialise a protobuff struct with the data I want  it to contain?

**Comment by globeriz** [comment]
I can confirm set_avatar works, it is not an issue with pgoapi

**Comment by TalSkverer** [comment]
I'm gonna answer in Python, because whatever:
```import PlayerAvatar_pb2
pa = PlayerAvatar_pb2.PlayerAvatar()
pa.skin  = 1 # Can use enum if it exists in Enum directory
... # initialize data
return pa.SerializeToString() # returns a serialized proto object. Make sure that's what the function expects

**Comment by jjordantb** [comment]
My current account is the the tutorial stage for setting avatar, and the following code is not setting avatar

code:
`pa = Player_pb2.PlayerAvatar()
pa.skin = 0
pa.hair = 0
pa.shirt = 0
pa.pants = 0
pa.hat = 0
pa.shoes = 0
pa.gender = Enums_pb2.MALE
pa.eyes = 0
pa.backpack = 0

request = api.create_request()
request.set_avatar(player_avatar=pa)
print(request.call())`
