### ISSUE TITLE
spiral_poi_search getting ServerSideRequestThrottlingException

### ISSUE THREAD

**Issue by gadzair** [keyphact/pgoapi#42]
pgoapi.exceptions.ServerSideRequestThrottlingException: Request throttled by server... slow down man

**Comment by gadzair** [comment]
Response dictionary: 
{   'api_url': u'pgorelease.nianticlabs.com/plfe/16',
    'request_id': 393756768215678530L,
    'responses': {   'GET_PLAYER': {   'player_data': {   'avatar': {   'pants': 1},
                                                          'contact_settings': {   },
                                                          'creation_timestamp_ms': 1469128031107L,
                                                          'currencies': [   {   'name': u'POKECOIN'},
                                                                            {   'amount': 100,
                                                                                'name': u'STARDUST'}],
                                                          'daily_bonus': {   },
                                                          'equipped_badge': {   },
                                                          'max_item_storage': 350,
                                                          'max_pokemon_storage': 250,
                                                          'tutorial_state': [   0,
                                                                                1,
                                                                                3,
                                                                                4,
                                                                                7],
                                                          'username': u'*******'},
                                       'success': True}},
    'status_code': 2}
2016-08-07 10:03:25,341 [    pgoapi] [ INFO] Creating a new direct request...
2016-08-07 10:03:25,341 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
2016-08-07 10:03:25,341 [    pgoapi] [ INFO] Execution of RPC
Traceback (most recent call last):
  File "spiral_poi_search.py", line 228, in <module>
    main()
  File "spiral_poi_search.py", line 159, in main
    find_poi(api, position[0], position[1])
  File "spiral_poi_search.py", line 176, in find_poi
    response_dict = api.get_map_objects(latitude = util.f2i(lat), longitude = util.f2i(lng), since_timestamp_ms = timestamps, cell_id = cell_ids)
  File "/Users/****/Downloads/PokemonGo-Map-t2/src/pgoapi/pgoapi/pgoapi.py", line 84, in function
    return request.call()
  File "/Users/****/Downloads/PokemonGo-Map-t2/src/pgoapi/pgoapi/pgoapi.py", line 182, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/Users/****/Downloads/PokemonGo-Map-t2/src/pgoapi/pgoapi/rpc_api.py", line 118, in request
    raise ServerSideRequestThrottlingException("Request throttled by server... slow down man")
pgoapi.exceptions.ServerSideRequestThrottlingException: Request throttled by server... slow down man

**Comment by xssc** [comment]
Self exploratory error..

**Comment by NoOne-dev** [comment]
Request reopening of issue

**Comment by keyphact** [comment]
Not sure why this needs to stay open?
I'll close and await a reason detailing why it does, and will re-open if there is a point to be made here with actions.

Thanks
