### ISSUE TITLE
is it possible to not set location?

### ISSUE THREAD

**Issue by earthchie** [keyphact/pgoapi#43]
Is it possible to not call ``api.set_position(*position)`` before attempting to login?

![image](https://cloud.githubusercontent.com/assets/7013039/17464645/10acba12-5d0e-11e6-89c2-ea601fbd589f.png)

It used to be fine in previous version (which is also working after 0.31). for example 
https://github.com/tejado/pgoapi/blob/1f06bc5488a86d5d459f22ea0ed4326f5e96b3ac/pgoapi/pgoapi.py

**Comment by HeinrichMeistere** [comment]
Is the new bot out?!

**Comment by earthchie** [comment]
kinda off-topic but yes.

**Comment by HeinrichMeistere** [comment]
Sry for off-topic but were can i get it?? :P Got it from a friend last time
xD

**Comment by elliottcarlson** [comment]
@earthchie It's necessary for the signature to be generated - so no.

**Comment by cheesynoob** [comment]
elliotcarlson is correct, your location is part of u20 and u10

**Comment by earthchie** [comment]
I see. I just want to access player's inventory. 
I'll stick with the old version then.

Thanks!

**Comment by DarkMatterMatt** [comment]
I don't think you can stick with the old version. The servers won't respond unless the get the valid codes, and the old version doesn't generate those codes (whereas the new version does).

**Comment by earthchie** [comment]
@DarkMatterMatt It can. You need to sign-request only map-related request. 

But I just need to access player inventory.
