### ISSUE TITLE
What are the default values for the new Signature ? 

### ISSUE THREAD

**Issue by mrik974** [keyphact/pgoapi#44]
I'm not a python expert (in fact I have never developed in python), and I have trouble finding the default values for the new Signature protobuf object. 
This [reddit comment](https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/d6776g2) says `Also all API requests will appear to Niantic to be coming from IOS users`.
I looked through the code of the API and I've been totally unable to find any reference to `iPhone` but a comment in [this file](https://github.com/keyphact/pgoapi/blob/master/pgoapi/protos/Signature.proto) saying `string firmware_brand = 10; // On Android: product.name, on iOS: "iPhone OS"`

I can't see where the default value for this is set, and I'm afraid it is finally not set at all. So I'm asking it here. Is there a default value for `firmware_brand` and the other keys ? If yes, where is it ? And does the api provide ways to override those values at the time?

**Comment by elliottcarlson** [comment]
This is handled by the signature lib (aka encrypt.dll/so)

**Comment by TalSkverer** [comment]
What you're lookimg at is the descriptor of a Signature messege, hence, it has no default values, and only what is set by the api will be sent to the server.

**Comment by MarlonColhado** [comment]
It is possible to decrypt the Unknown6 for Signature, thus changing only certain data? 
I am currently using this data:

**SensorInfo**
```
AccelNormalizedZ = 9.8,
AccelNormalizedX = 0.02,
AccelNormalizedY = 0.3,
TimestampSnapshot = (ulong)(ElapsedMilliseconds - 230L),
MagnetometerX = 0.012271042913198471,
MagnetometerY = -0.015570580959320068,
MagnetometerZ = 0.010850906372070313,
AngleNormalizedX = 17.950439453125,
AngleNormalizedY = -23.36273193359375,
AngleNormalizedZ = -48.8250732421875,
AccelRawX = -0.0120010357350111,
AccelRawY = -0.04214850440621376,
AccelRawZ = 0.94571763277053833,
GyroscopeRawX = 7.62939453125E-05,
GyroscopeRawY = -0.00054931640625,
GyroscopeRawZ = 0.0024566650390625,
AccelerometerAxes = 3L
```

**DeviceInfo**
```
DeviceId = "529e8aa6201f78b5",
AndroidBoardName = "msm8994",
AndroidBootloader = "unknown",
DeviceBrand = "OnePlus",
DeviceModel = "OnePlus2",
DeviceModelIdentifier = "ONE A2003_24_160604",
DeviceModelBoot = "qcom",
HardwareManufacturer = "OnePlus",
HardwareModel = "ONE A2003",
FirmwareBrand = "OnePlus2",
FirmwareTags = "dev-keys",
FirmwareType = "user",
FirmwareFingerprint = "OnePlus/OnePlus2/OnePlus2:6.0.1/MMB29M/1447840820:user/release-keys"
```

**LocationFix**
```
Provider = "network",
Latitude = latitudeVar,
Longitude = longitudeVar,
Altitude = altitudeVar,
TimestampSinceStart = (ulong)(ElapsedMilliseconds - 200L),
Floor = 3,
LocationType = 1L
```

**Comment by Acuchillar** [comment]
@MarlonColhado, you may want to sanitize your DeviceInfo if you have not already.  No need to have others copy/paste and get your _phone_ tagged because a thousand people are using it.

**Comment by cheesynoob** [comment]
You can see what goes into the signature by looking at signature_pb2.py we generate the details in rpc_api.py - I wouldn't worry about the data you send though, the only thing that is validated are the hashed fields which we painstakingly recreated.
