### ISSUE TITLE
How do I debug this?

### ISSUE THREAD

**Issue by bswan** [keyphact/pgoapi#51]
Hi, guys! I took pokecli.py example, edited it to fit my purpose but sometimes it crashes with no error at all. Console window just dissapering. How I can find error in that situation? Here is my code:

[edited.py.txt](https://github.com/keyphact/pgoapi/files/406441/edited.py.txt)

**Comment by ProLoDs** [comment]
try -d option

**Comment by bswan** [comment]
I tried it before, but even if it saying something before crash - I can't read it because console window closing. (I launching it from bat file with pause command so it must stay open, but it's closing)
P.S. I am not expierincing this kind of problem for last hour or two... Before it was pretty common... So I will wait untill it starts again and will try some way to write some kind of log to file... Or close this issue in day or two if it will not repeat

**Comment by elliottcarlson** [comment]
Launch it, or the bat file from the command line so when it errors it doesn't close the window.

**Comment by bswan** [comment]
It must not in any case. I belive it somehow crashes whole console system.

**Comment by ProLoDs** [comment]
pipe the output in a file...
with python runserver .....  > output.txt

**Comment by bswan** [comment]
Hm... That's what I was looking for. As I said I will try this when the will start repeatedly crash again. For now - it ok and stable.
