### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by mrlim0nad3** [keyphact/pgoapi#55]
hi guys, was wondering if someone can help with an installation guide. I can't see where i should add the account/password/location/gmap-key and then witch python file to run

thanks

**Comment by alxnegrila** [comment]
This is an API, not a full functional bot.

**Comment by Zeldafreak1990** [comment]
how do i install api

**Comment by elliottcarlson** [comment]
https://github.com/tejado/pgoapi/wiki

**Comment by globeriz** [comment]
active wiki link added to this repo's wiki, closing.

**Comment by BigChase** [comment]
The linked instructions now pertain to installing Pokemon GO MAP, not the PGOAPI.
