### ISSUE TITLE
Include encrypt in pgoapi

### ISSUE THREAD

**Issue by rirze** [keyphact/pgoapi#58]
Hey I was wondering if you guys were interested in distributing `encrypt.c` in this project as opposed to having people build it independently. If this idea is ok legally and/or distributing-wise, I can think of two solutions atm:

- Compile `encrypt.c` into `encrypt.so` with `python setup.py build_ext --inplace` and retain much of the code to be the same
- Write a cython wrapper that make its able to call the `encrypt` function directly from python. This involves using cython as a dependency and rewriting some the code to reflect this change. 

Let me know if this seems like a good idea and I can write up a pull request with whatever direction we have in mind.

**Comment by keyphact** [comment]
Unfortunately not I'm afraid. There are other places online where you can get it from.
