### ISSUE TITLE
TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'bytes'>, <class 'str'>)

### ISSUE THREAD

**Issue by jmangeja1** [keyphact/pgoapi#61]
I get this error after my auth token expires.

![screen shot 2016-08-08 at 4 42 21 pm](https://cloud.githubusercontent.com/assets/13386245/17500076/2290e810-5d87-11e6-9975-9fba9b3a0317.png)

**Comment by jmangeja1** [comment]
solved. was calling api.login

pw and username never stored in pgoapi object

**Comment by SamElvi** [comment]
how to fix this problome.l got this error when i used tensorflow image slim

**Comment by cindysillence** [comment]
I have also the same problem
