### ISSUE TITLE
HOW set_avatar

### ISSUE THREAD

**Issue by jjordantb** [keyphact/pgoapi#62]
Since the last issue was closed and I was unable to resolve my ignorance, I shall ask again...
I cannot get it to set avatar, (codename also seems to fail probably my ignorance)

You can bypass avatar by just sending the next tutorial stage packet:
http://i.imgur.com/80tcsee.jpg

Code:
from pgoapi.protos.POGOProtos.Data import Player_pb2
from pgoapi.protos.POGOProtos import Enums_pb2

api = pgoapi.PGoApi()
api.set_position(0,0,0) #i set correct position but don't want people to know my location
time.sleep(2)

if not api.login('ptc', username=username, password=password):
    sys.exit(1)

print('Successful login...')
time.sleep(2)

pa = Player_pb2.PlayerAvatar()
pa.skin = 2
pa.hair = 2
pa.shirt = 2
pa.pants = 2
pa.hat = 2
pa.shoes = 2
pa.gender = Enums_pb2.MALE
pa.eyes = 2
pa.backpack = 2

request = api.create_request()
request.set_avatar(player_avatar=pa) # have also tried pa.SerializeToString()
print(request.call())

**Comment by jjordantb** [comment]
I don't think @globeriz should be tagging inconpetence... Considering he can't read English half the time.

**Comment by cheesynoob** [comment]
The incompetence label is just a generic tag for when someone is asking for help with their code - This issue is not a problem with the API at all.

**Comment by jjordantb** [comment]
If only the documentation wasn't complete ass...
