### ISSUE TITLE
Not issue - New release of Pokemon Go.

### ISSUE THREAD

**Issue by takenek** [keyphact/pgoapi#71]
hey
Someone check what`s new in today release original Pokemon Go game for iOS/Androids?
I read on forum today there is a special function to detect real Pokemon Go clients and detect old clients and bots.

Someone can confirm this? Using bots is still safe after today update?
Anyone debug new version to check "what`s new" Pokemon Go Clients send to servers?
Mayby another UNK6 waiting in background?

Best Regards
TaKeN

**Comment by keyphact** [comment]
Not really an issue to be dealt with here.
