### ISSUE TITLE
How to use get_gym_details function?

### ISSUE THREAD

**Issue by legz** [keyphact/pgoapi#72]
I try to use  [get_gym_details](https://github.com/tejado/pgoapi/wiki/get_gym_details) to collect some info on the gyms around me but I can't figure how to use the function.
I tried this :
```
    gym={
        'gid':'0d39156d87f74263ac595d3ab2a2f728.16',
        'glatitude':45.876373,
        'glongitude':4.713474
        }
response= api.get_gym_details(gym_id = gym['gid'], gym_latitude = gym['glatitude'], gym_longitude = gym['glongitude'])
print('Response : \n\r{}'.format(pprint.PrettyPrinter(indent=4).pformat(response)))
```
But all I get is this:
```
...
[ INFO] Login process completed
[ INFO] Creating a new direct request...
[ INFO] Adding 'GET_GYM_DETAILS' to RPC request including arguments
[ INFO] Execution of RPC
[ INFO] Cleanup of request!
Response : 
{   'request_id': 746011827811372547L,
    'responses': {   'GET_GYM_DETAILS': {   'result': 2}},
    'status_code': 1}
```
Any idea on how to do a proper get_gym_details request please?

**Comment by globeriz** [comment]
You are missing some input parameters (`player_latitude` and `player_longitude`), please see POGOProtos for more information.

**Please also refrain from using the issues tab as your personal technical support section.**

**Comment by legz** [comment]
I though it was optional, thanks.
I updated my request with this :  
```
    gym={
        'gid':'7a7fcf27f2b848b2a8fc312a839471f9.11',
        'glatitude':45.773084,
        'glongitude':4.808241
        }
    response= api.get_gym_details(
        gym_id = gym['gid'],
        player_latitude = position[0],
        player_longitude = position[1],
        gym_latitude = gym['glatitude'],
        gym_longitude = gym['glongitude'])
    print('Response : \n\r{}'.format(pprint.PrettyPrinter(indent=4).pformat(response)))
```
but I have the exact same result.
(player position is 45.7730123, 4.8084165, there is 15m between player position and gym position.)

**Comment by zodiac** [comment]
@globeriz can you reproduce the bug with the updated request?
