### ISSUE TITLE
Example spiral_poi_search.py returns no pokemons nor poke-stops

### ISSUE THREAD

**Issue by mattiagalati** [keyphact/pgoapi#75]
Hi guys, first of all I want to thank you for your dedition for this project and for sharing it with us.
I need some help with you example cause when I run it everything runs fine but it returns no pokemons nor poke-stops.

I'm using this command:
`python spiral_poi_search.py -a google -u myusername@gmail.com -p mypass -l myCity`

I tried to dump the The request for map objects returns empty cells, there is only the cellID and the timestamp (see dumped response below)
```
{
   'status_code':1,
   'responses':{
      'GET_MAP_OBJECTS':{
         'status':1,
         'map_cells':[
            {
               's2_cell_id':1356396646480478208               L,
               'current_timestamp_ms':1470765031244               L
            },
            {
               's2_cell_id':1356396648627961856               L,
               'current_timestamp_ms':1470765031244               L
            },
            [AND SO ON]
         ]
      }
   },
   'request_id':473955141031952260   L
}
```
Final result:
`POI dictionary: 
{   'forts': [], 'pokemons': {   }}`

[Open this in a browser to see the path the spiral search took](http://maps.googleapis.com/maps/api/staticmap?size=400x400&path=44.2934414,8.4027633|44.2952742389,8.40280164074|44.2949732692,8.40427094435|44.2937696786,8.40430144289|44.2923794155,8.40434560448|44.2923889819,8.40302317122|44.2919758622,8.40139785873|44.2938040877,8.40150650977|44.295123026,8.4015051928|44.2969400722,8.40165275314|44.2968928607,8.4030243432|44.296520909,8.40470207047|44.296471179,8.40605389467|44.2950813131,8.40600927119|44.2934720606,8.40596673722|44.2920949597,8.40613017628|44.2905464488,8.40579613485|44.2908729018,8.40459484915|44.2904573766,8.40312251211|44.290447432,8.40140041892|44.2905842704,8.39997698584|44.2921269406,8.40019425724|44.2934983895,8.3998628839|44.2954026939,8.39992580224|44.2967167315,8.4000699958|44.2981968226,8.3998802563|44.2980012193,8.40129206878|44.2984196706,8.40308060595|44.2983806587,8.40439152467|44.2980960627,8.40601211847|44.2982194372,8.40739567428|44.2966218713,8.40740032344|44.2953532021,8.40771839271|44.2936918042,8.40766409075|44.2920084843,8.40762670119|44.2909320829,8.40745891307|44.2893832531,8.40728223926|44.2894233955,8.40579776104|44.289291136,8.40456565368|44.289284418,8.40297616144|44.2889836079,8.40152568601|44.2891043164,8.39988840266|44.2892733571,8.39860150789|44.2906342822,8.39865360833|44.2921628934,8.39839167756|44.2935134707,8.398332986|44.2949704231,8.39839281591|44.296504392,8.39876168845|44.298085916,8.39845944697)

**Comment by globeriz** [comment]
the example is rather outdated (it still uses the dreaded `f2i`), but examples are not priority fix, we will look into that when we have time

**Comment by mattiagalati** [comment]
Thank you. Now that I know the example is outdated, is there an example somewhere that can point me in the right direction? I mean time I will read the API documentation.
Thanks again.

**Comment by globeriz** [comment]
`pokecli.py` should be fine and uses `get_map_objects`

**Comment by BigChase** [comment]
I am getting the same "empty" response to get_map_objects calls in pokecli.py.  pokecli.py is also yielding nearly empty player_data records for all of 3 different authenticated users.

**Comment by ChrismCruz** [comment]
I am also getting empty response but this was working great as of 11:13AM this morning. Could someone confirm that it's still working or is it just me?

**Comment by wchill** [comment]
This might be a softban.

**Comment by mattiagalati** [comment]
Basing upon pokecli.py script and merging some utility functions from the spiral demo I have been able to create my own spiral search script and can confirm that the apis work well.
I have made the latest test yesterday night at 23:30 local time (Italy)
If I have time, I will correct the spiral example and submit to the authors, however, in order to familiarise with the responses, I suggest to dive into the scripts and figure out your own best solution.
