### ISSUE TITLE
encrypt.dll missing (WSL)

### ISSUE THREAD

**Issue by freemanovec** [keyphact/pgoapi#81]
Heya there,
I got the encrypt.dll for Windows x64.
I'm running Bash on Ubuntu on Windows [(MSDN Link)](https://msdn.microsoft.com/en-us/commandline/wsl/about)
I tried both compiling the Linux version and using the Windows version, but both fails.
I'm getting `OSError: encrypt.dll: cannot open shared object file: No such file or directory`
So I think the problem is that the program/python does not know where to look for this file. Is there a directory that is being searched for such .dlls or any command to add it to some env var?

**Comment by baskettcase** [comment]
for linux you most likely have a .so file instead of .dll and yes go ahead and try the full path.

**Comment by freemanovec** [comment]
Okay, absolute path got me somewhere. Now it throws another error. Ill open another issue for it as it isnt the problem described here.

**Comment by freemanovec** [comment]
I got it! I used an absolute path to an encrypt.so! Thanks all of you for helping and an awesome API ^^
