### ISSUE TITLE
lured pokestops may have issues

### ISSUE THREAD

**Issue by SkOODaT** [keyphact/pgoapi#83]
I have seen that the servers were restarted for PokemonGo version 0.33.0 this morning, around that time lured pokestops stoped showing up on many maps etc and thus could be affecting pokemon that spawn at them from showing, some people have suggested this could be an API change due to the new pokestop tracker system, not sure if this falls under the maps or the api but figured id post this :)

[PokemonGo-Map Issues #398](https://github.com/PokemonGoMap/PokemonGo-Map/issues/398)

**Comment by trisk** [comment]
It appears the `lure_info` field may have 1) been removed from pokéstops with active lures, or 2) only appears when encounters are available. This block of data remains on forts with lures:
```
                     "active_fort_modifier": {
                        "type": "Buffer",
                        "data": [
                            245,
                            3
                        ]
```

**Comment by trisk** [comment]
This shouldn't prevent Pokémon from appearing, I don't know if some other change is doing that.

**Comment by trisk** [comment]
Oh, right, FortData field 13 is actually messed up right now: #101

**Comment by SkOODaT** [comment]
i was out eariler tonight and we lured a stop for a brief second or 2 i could see the stop get lured on the map but immeidately it returns back to a regular stop, and i can confirm that lured pokemon are not displaying correctly either, i saw strange behaviour a few (2) of the lured pokemon did show up on the map but most did not .....

**Comment by keyphact** [comment]
Closing as this is topical and not directly caused nor managed by the API at present.
