### ISSUE TITLE
accept-tos.py has a hardcoded location

### ISSUE THREAD

**Issue by shark0der** [keyphact/pgoapi#93]
I hope I'm wrong but this might lead to account flagging

**Comment by TalSkverer** [comment]
It's an example script, be sure to edit it as needed, and no problem will ensue :)

**Comment by shark0der** [comment]
I know and I totally agree, I'm just saying that having a default most of people will use it, some of them maybe without knowing it so maybe a warning or a cli switch would be useful. Anyway, just my 2 cents, I don't really care since I'm not even using it :)

**Comment by TalSkverer** [comment]
^ Remove the hard-coded location, for our safety ;)
