### ISSUE TITLE
Empty results on catch_pokemon

### ISSUE THREAD

**Issue by dnsBlah** [keyphact/pgoapi#99]
Just from this morning I actually find 1 pokemon in a radius of 1000, once a while most of the times i find 0.
But the most frustrating part is that it doesn't catch at all!

My logic goes like this:
```
allObjects = getMapObjects
pokemons = filterPokemon(allObjects)
forts = filterForts(allObjects)
for pokemon in pokemons:
   walkAndCatch(pokemon)
for fort in forts
    walkAndSpin(fort)
    nPokemons = getMapObjects
```
I also do a pokemon search in the walkto every... 10 steps.

Now when I try to catch pokemons, 9/10 times I get a status_code 3 and empty result.
`{'status_code': 3, 'unknown6': [{'unknown2': {'unknown1': 1L}, 'response_type': 6}], 'responses': {'CATCH_POKEMON': {}}, 'request_id': 825875455527595912L}`

Is anyone facing this issue as well ??

**Comment by valmedia** [comment]
Status code 3. You account is banned.

**Comment by dnsBlah** [comment]
o great >.<

**Comment by baskettcase** [comment]
What type of ban is status code 3? soft ban or permanent ban? And is there somewhere that we can see all the status codes?

**Comment by dnsBlah** [comment]
status code 3 is not just a ban
it can mean a lot of things tho

**Comment by wchill** [comment]
3 usually means permaban.
